[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
disable_error_code = ["attr-defined"] # Adw not yet supported.

[tool.yapf]
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = false
